language: ruby
rvm:
  - 2.1.2
cache:
  - bundler
before_install: cd website
before_script:
  - psql -c 'create database openparliament_test;' -U admin
  - cp config/database.yml.travis config/database.yml
script: bundle exec rspec
