source 'https://rubygems.org'

gem 'rails', '4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'therubyracer', platforms: :ruby
gem 'jquery-rails'
gem 'jbuilder', '~> 1.2'
gem 'highcharts-rails', '~> 3.0.0'
gem 'wombat'
gem 'resque'
gem 'will_paginate', '~> 3.0'
gem 'less-rails-bootstrap'
gem 'font-awesome-rails'
gem 'puma'
gem 'yaml_db'

group :doc do
  gem 'sdoc', require: false
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'capistrano'
  gem 'capistrano-rails'
  gem 'capistrano-bundler'
  gem 'sqlite3'
end

group :production do
  gem 'pg'
end
