source 'https://rubygems.org'

ruby '2.2.3'

gem 'rails', '4.1.1'
gem 'uglifier', '>= 1.3.0'
gem 'therubyracer', platforms: :ruby
gem 'jquery-rails'
gem 'jbuilder', '~> 1.2'
gem 'resque'
gem 'will_paginate', '~> 3.0'
gem 'less-rails-bootstrap'
gem 'font-awesome-rails'
gem 'puma'
gem 'pg'
gem 'trollop'

group :doc do
  gem 'sdoc', require: false
end

group :development do
  gem 'quiet_assets'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'whenever', :require => false
  gem 'capistrano'
  gem 'capistrano-rails'
  gem 'capistrano-bundler'
  gem 'capistrano3-puma'
  gem 'rspec-rails'
  gem 'guard-rspec'
  gem 'pry'
  gem 'timecop'
end
