# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Session.create(
  date: Date.parse('2014-05-10'),
  stenograph: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla cursus lectus quis dolor viverra aliquet. Nullam consequat ultricies nulla, non condimentum arcu tempus nec. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis a interdum velit. Morbi pellentesque, lacus eu commodo fringilla, massa magna condimentum mi, a condimentum justo mi vel ex. Donec justo tortor, pharetra at libero ornare, congue dapibus sapien. Mauris viverra, orci ac pulvinar porttitor, mi ipsum cursus mauris, sed cursus enim odio ut sem. Donec euismod fermentum magna nec ullamcorper.
Phasellus vestibulum ut ligula at sollicitudin. Donec ultrices sed est nec ultricies. Sed tempor nisl dolor, ut placerat dui semper in. Nunc ullamcorper elit lacus, vel ullamcorper massa convallis eget. Nulla auctor tortor ut sem iaculis consequat. Sed ultrices arcu a lectus consectetur, vitae feugiat ligula sagittis. Curabitur vel urna vitae justo semper sollicitudin non sit amet leo. Cras tempus, libero non facilisis cursus, velit lectus varius nunc, eget egestas massa lacus nec eros. Cras tristique dui vel ex iaculis, sit amet vehicula odio vestibulum. Donec sagittis finibus purus. Quisque condimentum urna nunc, quis cursus velit volutpat at.
Praesent facilisis quam ac posuere facilisis. Donec lacus augue, volutpat quis vehicula id, fringilla ut purus. Phasellus molestie leo vel libero pulvinar, vel cursus arcu ornare. Aliquam ultricies eget diam at tempor. Morbi enim justo, pharetra vitae ligula at, luctus blandit lacus. Ut porttitor turpis at nisl faucibus, quis aliquet ex mattis. Donec ac tellus velit. Mauris vitae magna id sapien venenatis mollis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas scelerisque, velit vel placerat malesuada, purus risus convallis lorem, eu vehicula mauris sem vitae leo. Curabitur orci urna, pellentesque a mollis sit amet, sollicitudin vitae lectus. Nam mollis justo vitae ex viverra imperdiet. Fusce placerat odio aliquam nunc molestie feugiat. Duis ultrices condimentum velit, at interdum ipsum tempus eget. Praesent porttitor porta sem, id commodo arcu facilisis eu. In ligula velit, pretium id elementum eget, cursus laoreet lacus.
Nulla mi enim, sagittis vel auctor vitae, bibendum rutrum eros. Etiam viverra, elit ac dapibus maximus, orci eros sagittis sem, quis pellentesque mi libero vitae neque. Nunc semper, arcu at porta gravida, mi dui pretium massa, vitae elementum dui ex ac risus. Integer vel tempor metus. Donec tellus nisl, semper vitae massa eget, sagittis faucibus ex. In maximus elit a ultricies lobortis. Nunc in ipsum hendrerit, congue erat ac, lacinia lectus. Maecenas efficitur sed urna nec imperdiet. Nam et scelerisque diam, sed convallis eros. Quisque suscipit maximus faucibus. Aliquam tempor commodo maximus. Maecenas a ullamcorper arcu. Etiam arcu eros, viverra sit amet facilisis sed, feugiat sit amet lectus. Cras ullamcorper nisi ut purus vestibulum, quis sodales magna venenatis. Cras ultricies sollicitudin leo. Phasellus mollis eget diam vitae facilisis.
Nulla dolor mauris, mollis non magna non, scelerisque semper lorem. Nunc mattis dolor at est blandit finibus. Donec eget elementum dui. Sed in odio urna. Mauris venenatis molestie tortor eget porttitor. Curabitur malesuada turpis in neque accumsan blandit. In nec mauris tempus, placerat lectus nec, hendrerit sem. Proin sollicitudin massa eu dolor pharetra pulvinar. Duis nibh eros, pharetra in quam eu, pretium tristique lectus. Curabitur sollicitudin faucibus pharetra. In porttitor vel lectus iaculis ullamcorper. Morbi nulla lacus, blandit ullamcorper fermentum et, feugiat commodo lacus. Nulla dictum sapien semper, convallis lacus et, tempus est.
Vivamus condimentum sit amet nulla ac suscipit. Nulla suscipit elit augue, a elementum ligula pellentesque quis. Mauris sed orci velit. Integer nibh odio, facilisis lacinia iaculis et, viverra quis erat. Duis finibus viverra est finibus tincidunt. Sed dictum mauris vestibulum libero semper pharetra. Etiam non accumsan dui. Suspendisse cursus sapien ut lacus cursus semper. Curabitur porta laoreet enim nec faucibus. Cras pulvinar aliquam congue. Fusce rhoncus fringilla metus. Aliquam sit amet sollicitudin sem.
Ut turpis libero, convallis vel tortor ut, ornare aliquet quam. Quisque at mi finibus, commodo justo in, accumsan felis. Sed tempor vitae elit eu dapibus. Cras in vestibulum nibh, quis fringilla sem. Nulla sem tellus, sagittis et tellus sed, tincidunt porttitor massa. Suspendisse urna arcu, egestas at dapibus ut, scelerisque et ipsum. Praesent eget erat dictum, sollicitudin nunc sit amet, fermentum ipsum. Proin sit amet arcu varius, cursus augue eu, imperdiet ipsum. Donec risus orci, efficitur id suscipit eget, efficitur et dui. Nunc non posuere purus. Proin dapibus dui et maximus sagittis. Ut semper felis vulputate tincidunt sollicitudin. Nulla sed odio ut est hendrerit mattis a at lorem. Sed in leo hendrerit, sollicitudin turpis vel, sollicitudin massa. Proin placerat justo sem, interdum mollis purus vestibulum lacinia. Proin congue risus sit amet mauris pretium ornare.
Vestibulum varius pulvinar bibendum. Nulla facilisi. Sed eget felis quis purus vulputate cursus a a lacus. Nam hendrerit dolor id enim dignissim lacinia. Sed vehicula, nisl non suscipit viverra, mauris ipsum feugiat turpis, pellentesque hendrerit augue lacus a neque. Nunc maximus ullamcorper erat, ac lacinia velit finibus a. Nam eu lorem blandit libero porttitor venenatis non eget ipsum. Praesent et sapien suscipit, laoreet metus eget, consequat elit. Cras at ante vitae neque porttitor ullamcorper id quis elit. Praesent hendrerit aliquet nisi, id viverra orci luctus eget. Ut sit amet ultricies arcu. Cras lacinia et lectus congue fringilla. Nam in mattis sem. Fusce id neque molestie, eleifend lacus vitae, efficitur enim.
Pellentesque in blandit urna, et tincidunt leo. Ut lacinia sed augue eu volutpat. Nullam sollicitudin fringilla libero, sit amet molestie velit pulvinar at. Proin at ultricies leo. Donec blandit at dolor eu elementum. Quisque accumsan sem at eros consectetur euismod. Cras enim erat, sagittis nec libero non, venenatis vulputate arcu. Praesent sit amet convallis arcu. Etiam consectetur imperdiet ex pulvinar ullamcorper. Quisque scelerisque, lacus sed egestas gravida, nibh nunc lobortis neque, nec sodales erat nisi ac dui. Sed ac nisi sodales, molestie purus in, porta erat. Quisque laoreet, lacus sit amet scelerisque vestibulum, lorem nunc dignissim felis, ac luctus elit quam ullamcorper neque. Aenean cursus ex est.
Phasellus dictum justo feugiat, consequat tortor vitae, varius mi. Morbi eget augue ut arcu mattis molestie. Vestibulum libero sapien, posuere non quam nec, imperdiet ultrices turpis. Aenean vel ipsum accumsan orci interdum pellentesque. Vivamus faucibus quis risus sit amet ultricies. Sed leo velit, aliquet eu sem eget, dignissim euismod metus. Proin ut hendrerit turpis, at accumsan leo. In in tellus magna. Duis non dui imperdiet, pulvinar ligula eget, feugiat arcu. Vivamus eros est, dictum sit amet erat porta, elementum sollicitudin ipsum. Donec sodales lectus sed ex feugiat laoreet id et sapien.',
  structure: Structure.create(
    kind: :assembly,
    name: 'Подли гадове IV',
    start_date: Date.parse('2014-01-01'),
    end_date: Date.parse('2014-12-01')
  )
)

Session.create(
  date: Date.parse('2013-05-10'),
  stenograph: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla cursus lectus quis dolor viverra aliquet. Nullam consequat ultricies nulla, non condimentum arcu tempus nec. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis a interdum velit. Morbi pellentesque, lacus eu commodo fringilla, massa magna condimentum mi, a condimentum justo mi vel ex. Donec justo tortor, pharetra at libero ornare, congue dapibus sapien. Mauris viverra, orci ac pulvinar porttitor, mi ipsum cursus mauris, sed cursus enim odio ut sem. Donec euismod fermentum magna nec ullamcorper.',
  structure: Structure.last
)

Session.create(
  date: Date.parse('2014-05-11'),
  stenograph: 'Bacon ipsum dolor sit amet beef meatloaf beef ribs, ribeye sausage salami chicken pig. Pig short ribs ground round tri-tip swine. Brisket pork chop boudin, tenderloin short loin ground round filet mignon kielbasa hamburger meatloaf prosciutto pork. Jowl ground round tri-tip shank capicola kielbasa meatloaf turducken landjaeger pig frankfurter. Swine meatloaf jowl, tenderloin pork loin beef ribs bresaola shank ribeye brisket bacon leberkas short loin.
Porchetta cow biltong corned beef, kielbasa pork pig kevin andouille chicken t-bone turducken. Turducken venison swine brisket andouille. T-bone fatback turducken filet mignon. Leberkas capicola kielbasa, ground round filet mignon bacon pork chop bresaola strip steak doner ribeye frankfurter biltong short loin andouille.
Cow boudin meatball, hamburger filet mignon spare ribs chicken rump pancetta bacon tri-tip short loin shankle andouille. Tenderloin leberkas chicken flank shank, ball tip landjaeger filet mignon jowl pork chop venison porchetta beef ribs. Turducken porchetta jerky short loin, ball tip spare ribs drumstick ribeye shankle turkey fatback flank. Prosciutto drumstick strip steak tenderloin swine. Chuck pork chop landjaeger short loin meatloaf. Chicken leberkas prosciutto cow pork loin.
Pork loin tongue short ribs cow boudin ball tip pork sausage capicola meatball doner strip steak swine t-bone. Bacon drumstick jerky, turkey short ribs corned beef andouille pig tri-tip tongue pork loin kevin frankfurter. Pig pancetta turkey hamburger short loin sirloin pork, boudin filet mignon flank. Biltong pork loin swine tenderloin short ribs. Chicken capicola shankle, tenderloin meatball pastrami rump tongue cow.
Turducken beef ribs tongue leberkas tri-tip, short ribs tenderloin venison. Spare ribs shankle ribeye pancetta leberkas fatback. Strip steak capicola doner meatloaf pig. Strip steak rump swine short loin ball tip.
Frankfurter doner cow sausage boudin ham hock. Bacon shoulder porchetta pastrami meatball. Chuck ribeye pork belly chicken. Pancetta bresaola hamburger pork loin, shankle meatball pork belly strip steak flank. Shank filet mignon prosciutto tenderloin ground round capicola jowl short loin cow boudin shoulder kielbasa jerky short ribs. Ball tip jowl shoulder hamburger pork belly shank sirloin. Doner turkey drumstick tongue, tail shank ham hock short loin.
Shankle meatball pancetta, porchetta fatback short ribs biltong capicola jowl frankfurter ham hock pork loin jerky ground round sirloin. Chuck hamburger pork loin jerky, tenderloin bacon rump kevin drumstick filet mignon ribeye. Brisket porchetta pig rump pancetta doner. Fatback sirloin swine bacon biltong chicken spare ribs. Sausage flank bacon, ball tip pork pork belly spare ribs leberkas brisket shank turkey sirloin. Sirloin pork shoulder pork loin andouille ham hock. Ribeye rump sirloin, fatback bacon venison sausage kevin.
Leberkas pastrami kevin swine flank, doner meatloaf turkey. Flank capicola ham hock, boudin chuck pancetta shankle rump jowl kielbasa pastrami brisket pork. Jerky chicken ribeye beef hamburger. Jerky leberkas meatball shankle capicola t-bone fatback, sausage pork chop boudin sirloin chuck strip steak andouille drumstick.
Kielbasa pork chop jerky ground round shankle andouille. Short ribs venison boudin porchetta ham hock hamburger biltong ball tip swine frankfurter rump, shank prosciutto meatloaf. Meatloaf bresaola venison ball tip salami kielbasa, fatback swine pork chop bacon tenderloin flank tri-tip tongue turducken. Hamburger ball tip ham venison cow. Corned beef tail jowl ball tip sirloin beef ribs, beef pancetta pork belly meatball chuck pork chop ham landjaeger frankfurter.
Sirloin turkey hamburger prosciutto, shoulder meatloaf tail strip steak. Sirloin pork loin t-bone doner. Meatball pork chop ground round turkey tongue tail brisket bresaola leberkas pork loin prosciutto pancetta jerky. Chuck bacon short ribs pig drumstick rump leberkas turkey.',
  structure: Structure.last
)

